title: node-tail
description: Your zero depenency NodeJS package for tailing files
google_analytics: UA-1839356-1
show_downloads: false
theme: jekyll-theme-minimal
url: https://www.lucagrulla.com

gems:
  - jekyll-mentions
